JSONDecodeFailed: Failed to decode JSON data
URLDecodeFailed: Failed to decode URL
NotAuthenticated: Not Authenticated
NotAuthorized: Not Authorized
InvalidUsername: Invalid Username
InvalidPassword: Invalid Password
InvalidUsernamePassword: Invalid username or password
NoEmailAddress: No email address found
MissingResetToken: Missing reset token
InvalidResetToken: Invalid reset token
PasswordMismatch: Passwords do not match
