NotAuthenticated: Not Authenticated
NotAuthorized: Not Authorized
InvalidUsername: Invalid username
InvalidPassword: Invalid password
InvalidUsernamePassword: Invalid username or password
NoEmailAddress: No email address found
MissingResetToken: Missing reset token
InvalidResetToken: Invalid reset token
ExpiredResetToken: The password reset link you used has expired. You must request a new reset link.
PasswordInternalError: Your request could not be processed. You probably need to contact technical support to resolve this issue.
PasswordMismatch: Passwords do not match
SendmailError: A server configuration error prevented an email from being sent. Please contact us directly
UnacceptablePassword msg@Text: Unacceptable Password. #{msg}
CoreError e@CoreError: #{renderMessage HappstackAuthenticateI18N ["en"] e}
