NotAuthenticated: Not Authenticated
NotAuthorized: Not Authorized
InvalidUsername: Invalid Username
InvalidPassword: Invalid Password
InvalidUsernamePassword: Invalid username or password
NoEmailAddress: No email address found
MissingResetToken: Missing reset token
InvalidResetToken: Invalid reset token
PasswordMismatch: Passwords do not match
SendmailError: A server configuration error prevented an email from being sent. Please contact us directly
UnacceptablePassword msg@Text: Unacceptable Password. #{msg}
CoreError e@CoreError: #{renderMessage HappstackAuthenticateI18N ["en"] e}
