UsernameMsg: username
EmailMsg: email
PasswordMsg: password
PasswordConfirmationMsg: password confirmation
SignUpMsg: sign up
SignInMsg: sign in
LogoutMsg: logout
OldPasswordMsg: old password
NewPasswordMsg: new password
NewPasswordConfirmationMsg: new password confirmation
ChangePasswordMsg: change password
RequestPasswordResetMsg: request password reset
ChangePasswordAuthRequiredMsg: Can not change password because you are not logged in.
PasswordChangedMsg: Password successfully updated

